# Generated by Django 3.1.2 on 2021-10-09 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Новость'),
        ),
    ]
