# Generated by Django 3.2.8 on 2021-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0002_auto_20211009_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='head_img',
            field=models.ImageField(default=None, null=True, upload_to='head_imgs', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
