# Generated by Django 3.2.8 on 2021-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0003_auto_20211009_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_add',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
