# Generated by Django 3.2.8 on 2021-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0004_news_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='head_imgs', verbose_name='Изображение'),
        ),
    ]
