# Generated by Django 3.2.8 on 2021-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0005_alter_news_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Название новости'),
        ),
    ]
