# Generated by Django 3.2.8 on 2021-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0006_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_add',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
