# Generated by Django 3.2.8 on 2021-10-09 15:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0007_alter_news_date_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Название акции')),
                ('head_img', models.ImageField(blank=True, default=None, null=True, upload_to='head_imgs', verbose_name='Изображение')),
                ('body', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Акция')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
