# Generated by Django 3.2.8 on 2021-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0008_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='date_work',
            field=models.CharField(default='', max_length=100, verbose_name='Время работы'),
        ),
    ]
