# Generated by Django 3.2.8 on 2021-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_oil', '0011_stocks_name_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='name_url',
            field=models.CharField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
